language: php

php:
  - 7.1
  - 7.2
  - 7.3

services:
  - mysql

dist: bionic

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --no-progress
  - mysql -u root -e 'CREATE DATABASE IF NOT EXISTS test;'
  - sudo apt-get install php7.2-mysql
  - cd $TRAVIS_BUILD_DIR

script:
  - composer check-all

