plugins:
  - jekyll-include-cache

#remote_theme: benbalter/retlab
remote_theme: "mmistakes/minimal-mistakes@4.17.1"

# Name of your site (displayed in the header)
name: Slim 4 skeleton

# Name of website (site.title)
title: Slim 4 skeleton

# Short description of your site
description: A PHP example application
