name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 33306:3306

    steps:
    - uses: actions/checkout@v1

    - name: Creat test table
      run: mysql -uroot -proot -e 'CREATE DATABASE IF NOT EXISTS test;'

    - name: Copy settings
      run: cp config/env.example.php config/env.php

    - name: Update mysql password
      run: sed -i s/\'\';/\'root\';/g config/env.php

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install tables
      run: composer migrate

    - name: Run test suite
      run: composer check-all
